---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: ocs-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1024Gi
  storageClassName: rook-ceph-block
